### ISSUE TITLE
Drain node doesn't work after reboot

### ISSUE THREAD

**Issue by e0ne** [k8snetworkplumbingwg/sriov-network-operator#322]
After node is rebooted operator doesn't drain node. It leads to non-working workloads on a rebooted node

**Comment by adrianchiris** [comment]
@SchSeba have you encountered this in Openshift ?

**Comment by adrianchiris** [comment]
So i assume the check is there since, when moving from zero to non-zero number of VFs it is assumed that there are no pods consuming VFs which makes drain operation not needed.

now, say we have a deployment with pods running on a node (these pods have sriov secondary network).

On node reboot. if node comes up "fast" enough the pods of the deployment will not get rescheduled.
then kubelet will spin them up when it comes up. at that point i expect CNI call to fail and pod to enter error state.

@e0ne is that the case ?

**Comment by SchSeba** [comment]
@adrianchiris we see this in OCP also and there is an open issue on k8s (kubelet) for it https://github.com/kubernetes/kubernetes/issues/109595

can you try to remove the checkpoint file from kubelet on reboot that should stuck the pods on pending until the device plugin is really ready

**Comment by adrianchiris** [comment]
thanks for linking the k8s issue.

So, until this is sorted, i think we should introduce a temporary fix in sriov network operator to avoid such cases.
for that i think drain is the correct way to go as this (node reboot) is not something is expected to happen often.
(with a TODO to remove it ofc)

id prefer to avoid deleting kubelet cache files in system service, this feels to me like adding un-needed complexity which also tinkers with a critical component that we don't really own (and might have un-intentional side effects ).
