### ISSUE TITLE
Release SRIOV Network Operator V1.3.0

### ISSUE THREAD

**Issue by adrianchiris** [k8snetworkplumbingwg/sriov-network-operator#450]
Its been a while since we released sriov network operator.
lets do a new release.

PR wish list:

- [x] #365 
- [x] #427 
- [x] #435 
- [x] #436 
- [x] #553
- [x] #555

We should also do a release in dependent projects (CNIs, Device Plugins, etc)

@SchSeba @e0ne @e0ne @zeeke and others, feel free to add in.

**Comment by e0ne** [comment]
#365 is merged and will be a part of the upcomint release

**Comment by jslouisyou** [comment]
Hello, Is there any plan for release latest 1.3.0 version?

**Comment by dastonzerg** [comment]
+1 To this, we saw some issues recently like when `sriov-network-config-daemon` starts, the cluster api server may not be ready and `InitNicIDMap` just fails silently which leaves the configMap go struct to be empty and none of the network interfaces will be considered as supported. The fix is in "Dec 14, 2022 " https://github.com/k8snetworkplumbingwg/sriov-network-operator/commit/b92f9846fe61e22113427dd9f136a92a3e6d44fd master already but not included in any releases yet.

If we can have a new release 1.3.0 soon that would be greatly helpful.

**Comment by SchSeba** [comment]
I added the parallel draining into the list

**Comment by adrianchiris** [comment]
Let me add this to our weekly meeting for tracking. we should have a new version released.

**Comment by cyclinder** [comment]
Hi, https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/555 has been merged, Do you have any plans for a new release v1.3.0?

**Comment by SchSeba** [comment]
closing this one as we made a release
